# Generated by Django 2.1.5 on 2020-09-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('op_id', models.IntegerField(primary_key=True, serialize=False)),
                ('op_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('q_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relation_Question_Opn',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rel_opid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Options')),
                ('rel_qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
            options={
                'db_table': 'relation_question_opn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relation_Survey_Qn',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rel_last', models.IntegerField()),
                ('rel_qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
            options={
                'db_table': 'relation_survery_qn',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_desc', models.CharField(max_length=255)),
                ('s_start', models.DateTimeField()),
                ('s_end', models.DateTimeField()),
                ('s_active', models.IntegerField()),
            ],
            options={
                'db_table': 'survey',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='relation_survey_qn',
            name='rel_sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
